export interface Language {
  id: string;
  name: string;
  aliases?: string[];
}

export const LANGUAGES: Language[] = [
  { id: 'plaintext', name: 'Plain Text' },
  { id: 'javascript', name: 'JavaScript', aliases: ['js'] },
  { id: 'typescript', name: 'TypeScript', aliases: ['ts'] },
  { id: 'python', name: 'Python', aliases: ['py'] },
  { id: 'java', name: 'Java' },
  { id: 'csharp', name: 'C#', aliases: ['cs', 'c-sharp'] },
  { id: 'cpp', name: 'C++', aliases: ['c++', 'cplusplus'] },
  { id: 'c', name: 'C' },
  { id: 'go', name: 'Go', aliases: ['golang'] },
  { id: 'rust', name: 'Rust', aliases: ['rs'] },
  { id: 'ruby', name: 'Ruby', aliases: ['rb'] },
  { id: 'php', name: 'PHP' },
  { id: 'swift', name: 'Swift' },
  { id: 'kotlin', name: 'Kotlin', aliases: ['kt'] },
  { id: 'scala', name: 'Scala' },
  { id: 'html', name: 'HTML' },
  { id: 'css', name: 'CSS' },
  { id: 'scss', name: 'SCSS', aliases: ['sass'] },
  { id: 'less', name: 'Less' },
  { id: 'json', name: 'JSON' },
  { id: 'jsonc', name: 'JSON with Comments', aliases: ['jsonc'] },
  { id: 'json5', name: 'JSON5' },
  { id: 'yaml', name: 'YAML', aliases: ['yml'] },
  { id: 'xml', name: 'XML' },
  { id: 'markdown', name: 'Markdown', aliases: ['md'] },
  { id: 'sql', name: 'SQL' },
  { id: 'shell', name: 'Shell', aliases: ['bash', 'sh', 'zsh'] },
  { id: 'powershell', name: 'PowerShell', aliases: ['ps1', 'pwsh'] },
  { id: 'dockerfile', name: 'Dockerfile', aliases: ['docker'] },
  { id: 'nginx', name: 'Nginx' },
  { id: 'graphql', name: 'GraphQL', aliases: ['gql'] },
  { id: 'vue', name: 'Vue' },
  { id: 'vue-html', name: 'Vue HTML' },
  { id: 'svelte', name: 'Svelte' },
  { id: 'jsx', name: 'JSX' },
  { id: 'tsx', name: 'TSX' },
  { id: 'astro', name: 'Astro' },
  { id: 'angular-html', name: 'Angular HTML' },
  { id: 'angular-ts', name: 'Angular TypeScript' },
  { id: 'haskell', name: 'Haskell', aliases: ['hs'] },
  { id: 'erlang', name: 'Erlang', aliases: ['erl'] },
  { id: 'elixir', name: 'Elixir', aliases: ['ex', 'exs'] },
  { id: 'clojure', name: 'Clojure', aliases: ['clj'] },
  { id: 'fsharp', name: 'F#', aliases: ['fs', 'f-sharp'] },
  { id: 'ocaml', name: 'OCaml', aliases: ['ml'] },
  { id: 'reasonml', name: 'ReasonML', aliases: ['reason'] },
  { id: 'purescript', name: 'PureScript', aliases: ['purs'] },
  { id: 'elm', name: 'Elm' },
  { id: 'lua', name: 'Lua' },
  { id: 'perl', name: 'Perl', aliases: ['pl'] },
  { id: 'r', name: 'R' },
  { id: 'julia', name: 'Julia', aliases: ['jl'] },
  { id: 'matlab', name: 'MATLAB' },
  { id: 'fortran-free-form', name: 'Fortran', aliases: ['f90', 'f95'] },
  { id: 'cobol', name: 'COBOL', aliases: ['cob'] },
  { id: 'pascal', name: 'Pascal', aliases: ['pas'] },
  { id: 'delphi', name: 'Delphi' },
  { id: 'ada', name: 'Ada' },
  { id: 'assembly', name: 'Assembly', aliases: ['asm'] },
  { id: 'wasm', name: 'WebAssembly', aliases: ['wat'] },
  { id: 'llvm', name: 'LLVM IR' },
  { id: 'objective-c', name: 'Objective-C', aliases: ['objc', 'm'] },
  { id: 'objective-cpp', name: 'Objective-C++', aliases: ['objcpp', 'mm'] },
  { id: 'd', name: 'D' },
  { id: 'nim', name: 'Nim' },
  { id: 'crystal', name: 'Crystal', aliases: ['cr'] },
  { id: 'zig', name: 'Zig' },
  { id: 'v', name: 'V' },
  { id: 'odin', name: 'Odin' },
  { id: 'dart', name: 'Dart' },
  { id: 'groovy', name: 'Groovy' },
  { id: 'gradle', name: 'Gradle' },
  { id: 'maven', name: 'Maven POM', aliases: ['pom'] },
  { id: 'sbt', name: 'SBT' },
  { id: 'apex', name: 'Apex' },
  { id: 'visualforce', name: 'Visualforce' },
  { id: 'abap', name: 'ABAP' },
  { id: 'plsql', name: 'PL/SQL' },
  { id: 'tsql', name: 'T-SQL', aliases: ['transact-sql'] },
  { id: 'sparql', name: 'SPARQL' },
  { id: 'cypher', name: 'Cypher' },
  { id: 'cql', name: 'CQL' },
  { id: 'prolog', name: 'Prolog' },
  { id: 'lisp', name: 'Lisp' },
  { id: 'scheme', name: 'Scheme', aliases: ['scm'] },
  { id: 'racket', name: 'Racket', aliases: ['rkt'] },
  { id: 'common-lisp', name: 'Common Lisp', aliases: ['cl'] },
  { id: 'emacs-lisp', name: 'Emacs Lisp', aliases: ['elisp'] },
  { id: 'vimscript', name: 'Vimscript', aliases: ['vim'] },
  { id: 'viml', name: 'VimL' },
  { id: 'awk', name: 'AWK' },
  { id: 'sed', name: 'sed' },
  { id: 'make', name: 'Makefile', aliases: ['makefile'] },
  { id: 'cmake', name: 'CMake' },
  { id: 'meson', name: 'Meson' },
  { id: 'ninja', name: 'Ninja' },
  { id: 'bazel', name: 'Bazel', aliases: ['starlark'] },
  { id: 'terraform', name: 'Terraform', aliases: ['tf', 'hcl'] },
  { id: 'bicep', name: 'Bicep' },
  { id: 'puppet', name: 'Puppet', aliases: ['pp'] },
  { id: 'ansible', name: 'Ansible' },
  { id: 'saltstack', name: 'SaltStack', aliases: ['sls'] },
  { id: 'nix', name: 'Nix' },
  { id: 'dhall', name: 'Dhall' },
  { id: 'jsonnet', name: 'Jsonnet' },
  { id: 'cue', name: 'CUE' },
  { id: 'rego', name: 'Rego' },
  { id: 'docker-compose', name: 'Docker Compose', aliases: ['compose'] },
  { id: 'kubernetes', name: 'Kubernetes', aliases: ['k8s'] },
  { id: 'helm', name: 'Helm' },
  { id: 'toml', name: 'TOML' },
  { id: 'ini', name: 'INI' },
  { id: 'properties', name: 'Properties' },
  { id: 'dotenv', name: 'dotenv', aliases: ['env'] },
  { id: 'editorconfig', name: 'EditorConfig' },
  { id: 'gitignore', name: 'Git Ignore' },
  { id: 'gitattributes', name: 'Git Attributes' },
  { id: 'gitconfig', name: 'Git Config' },
  { id: 'diff', name: 'Diff', aliases: ['patch'] },
  { id: 'log', name: 'Log' },
  { id: 'csv', name: 'CSV' },
  { id: 'tsv', name: 'TSV' },
  { id: 'latex', name: 'LaTeX', aliases: ['tex'] },
  { id: 'bibtex', name: 'BibTeX', aliases: ['bib'] },
  { id: 'asciidoc', name: 'AsciiDoc', aliases: ['adoc'] },
  { id: 'rst', name: 'reStructuredText', aliases: ['restructuredtext'] },
  { id: 'org', name: 'Org Mode' },
  { id: 'textile', name: 'Textile' },
  { id: 'haml', name: 'Haml' },
  { id: 'slim', name: 'Slim' },
  { id: 'pug', name: 'Pug', aliases: ['jade'] },
  { id: 'ejs', name: 'EJS' },
  { id: 'erb', name: 'ERB', aliases: ['eruby'] },
  { id: 'handlebars', name: 'Handlebars', aliases: ['hbs'] },
  { id: 'mustache', name: 'Mustache' },
  { id: 'liquid', name: 'Liquid' },
  { id: 'twig', name: 'Twig' },
  { id: 'blade', name: 'Blade' },
  { id: 'jinja', name: 'Jinja', aliases: ['jinja2'] },
  { id: 'nunjucks', name: 'Nunjucks', aliases: ['njk'] },
  { id: 'velocity', name: 'Velocity', aliases: ['vtl'] },
  { id: 'freemarker', name: 'FreeMarker', aliases: ['ftl'] },
  { id: 'thymeleaf', name: 'Thymeleaf' },
  { id: 'razor', name: 'Razor', aliases: ['cshtml'] },
  { id: 'asp-net-razor', name: 'ASP.NET Razor' },
  { id: 'jsp', name: 'JSP' },
  { id: 'gsp', name: 'GSP' },
  { id: 'xsl', name: 'XSL', aliases: ['xslt'] },
  { id: 'xpath', name: 'XPath' },
  { id: 'xquery', name: 'XQuery' },
  { id: 'wgsl', name: 'WGSL' },
  { id: 'glsl', name: 'GLSL' },
  { id: 'hlsl', name: 'HLSL' },
  { id: 'cuda', name: 'CUDA', aliases: ['cu'] },
  { id: 'opencl', name: 'OpenCL', aliases: ['cl'] },
  { id: 'metal', name: 'Metal' },
  { id: 'gdscript', name: 'GDScript', aliases: ['gd'] },
  { id: 'gdshader', name: 'GDShader' },
  { id: 'shaderlab', name: 'ShaderLab' },
  { id: 'unity', name: 'Unity' },
  { id: 'unreal', name: 'Unreal' },
  { id: 'solidity', name: 'Solidity', aliases: ['sol'] },
  { id: 'vyper', name: 'Vyper', aliases: ['vy'] },
  { id: 'move', name: 'Move' },
  { id: 'cairo', name: 'Cairo' },
  { id: 'clarity', name: 'Clarity' },
  { id: 'tact', name: 'Tact' },
  { id: 'func', name: 'FunC' },
  { id: 'proto', name: 'Protocol Buffers', aliases: ['protobuf'] },
  { id: 'thrift', name: 'Thrift' },
  { id: 'avro', name: 'Avro' },
  { id: 'capnp', name: "Cap'n Proto" },
  { id: 'flatbuffers', name: 'FlatBuffers', aliases: ['fbs'] },
  { id: 'smithy', name: 'Smithy' },
  { id: 'openapi', name: 'OpenAPI', aliases: ['swagger'] },
  { id: 'asyncapi', name: 'AsyncAPI' },
  { id: 'prisma', name: 'Prisma' },
  { id: 'typespec', name: 'TypeSpec' },
  { id: 'http', name: 'HTTP' },
  { id: 'rest', name: 'REST' },
  { id: 'grpc', name: 'gRPC' },
  { id: 'mermaid', name: 'Mermaid' },
  { id: 'plantuml', name: 'PlantUML' },
  { id: 'dot', name: 'Graphviz DOT', aliases: ['graphviz'] },
  { id: 'd2', name: 'D2' },
  { id: 'verilog', name: 'Verilog', aliases: ['v'] },
  { id: 'systemverilog', name: 'SystemVerilog', aliases: ['sv'] },
  { id: 'vhdl', name: 'VHDL' },
  { id: 'tcl', name: 'Tcl' },
  { id: 'spice', name: 'SPICE' },
  { id: 'hcl', name: 'HCL' },
  { id: 'packer', name: 'Packer' },
  { id: 'vagrant', name: 'Vagrant' },
  { id: 'cloudformation', name: 'CloudFormation', aliases: ['cfn'] },
  { id: 'arm-template', name: 'ARM Template' },
  { id: 'pulumi', name: 'Pulumi' },
  { id: 'stylus', name: 'Stylus', aliases: ['styl'] },
  { id: 'postcss', name: 'PostCSS' },
  { id: 'tailwindcss', name: 'Tailwind CSS' },
  { id: 'coffeescript', name: 'CoffeeScript', aliases: ['coffee'] },
  { id: 'livescript', name: 'LiveScript', aliases: ['ls'] },
  { id: 'imba', name: 'Imba' },
  { id: 'marko', name: 'Marko' },
  { id: 'mdx', name: 'MDX' },
  { id: 'soql', name: 'SOQL' },
  { id: 'sosl', name: 'SOSL' },
  { id: 'azcli', name: 'Azure CLI' },
  { id: 'kusto', name: 'Kusto', aliases: ['kql'] },
  { id: 'wolfram', name: 'Wolfram', aliases: ['mathematica', 'wl'] },
  { id: 'maple', name: 'Maple' },
  { id: 'maxima', name: 'Maxima' },
  { id: 'sage', name: 'SageMath' },
  { id: 'stata', name: 'Stata' },
  { id: 'sas', name: 'SAS' },
  { id: 'spss', name: 'SPSS' },
  { id: 'stan', name: 'Stan' },
  { id: 'jags', name: 'JAGS' },
  { id: 'bugs', name: 'BUGS' },
  { id: 'lean', name: 'Lean', aliases: ['lean4'] },
  { id: 'coq', name: 'Coq' },
  { id: 'agda', name: 'Agda' },
  { id: 'idris', name: 'Idris' },
  { id: 'isabelle', name: 'Isabelle' },
  { id: 'tla', name: 'TLA+' },
  { id: 'alloy', name: 'Alloy' },
  { id: 'z3', name: 'Z3' },
  { id: 'smt', name: 'SMT-LIB', aliases: ['smtlib'] },
  { id: 'reg', name: 'Windows Registry' },
  { id: 'bat', name: 'Batch', aliases: ['batch', 'cmd'] },
  { id: 'vb', name: 'Visual Basic', aliases: ['vba', 'vbs'] },
  { id: 'vbnet', name: 'VB.NET' },
  { id: 'asp', name: 'Classic ASP' },
  { id: 'actionscript', name: 'ActionScript', aliases: ['as'] },
  { id: 'haxe', name: 'Haxe', aliases: ['hx'] },
  { id: 'smalltalk', name: 'Smalltalk', aliases: ['st'] },
  { id: 'forth', name: 'Forth' },
  { id: 'factor', name: 'Factor' },
  { id: 'red', name: 'Red' },
  { id: 'rebol', name: 'REBOL' },
  { id: 'io', name: 'Io' },
  { id: 'ioke', name: 'Ioke' },
  { id: 'fantom', name: 'Fantom' },
  { id: 'gosu', name: 'Gosu' },
  { id: 'ceylon', name: 'Ceylon' },
  { id: 'xtend', name: 'Xtend' },
  { id: 'xbase', name: 'xBase', aliases: ['clipper', 'foxpro'] },
  { id: 'pony', name: 'Pony' },
  { id: 'ballerina', name: 'Ballerina', aliases: ['bal'] },
  { id: 'boss', name: 'BOSS' },
  { id: 'bsl', name: '1C Enterprise', aliases: ['1c'] },
  { id: 'applescript', name: 'AppleScript', aliases: ['osascript'] },
  { id: 'fish', name: 'Fish' },
  { id: 'nu', name: 'Nushell' },
  { id: 'elvish', name: 'Elvish' },
  { id: 'oil', name: 'Oil' },
  { id: 'xonsh', name: 'Xonsh' },
  { id: 'raku', name: 'Raku', aliases: ['perl6', 'p6'] },
  { id: 'hy', name: 'Hy' },
  { id: 'fennel', name: 'Fennel', aliases: ['fnl'] },
  { id: 'janet', name: 'Janet' },
  { id: 'picolisp', name: 'PicoLisp' },
  { id: 'arc', name: 'Arc' },
  { id: 'shen', name: 'Shen' },
  { id: 'lfe', name: 'LFE' },
  { id: 'gleam', name: 'Gleam' },
  { id: 'unison', name: 'Unison' },
  { id: 'koka', name: 'Koka' },
  { id: 'eff', name: 'Eff' },
  { id: 'frank', name: 'Frank' },
  { id: 'links', name: 'Links' },
  { id: 'ur', name: 'Ur/Web' },
  { id: 'sml', name: 'Standard ML' },
  { id: 'mlton', name: 'MLton' },
  { id: 'poly', name: 'Poly/ML' },
  { id: 'alice', name: 'Alice ML' },
  { id: 'ciao', name: 'Ciao' },
  { id: 'mercury', name: 'Mercury' },
  { id: 'curry', name: 'Curry' },
  { id: 'oz', name: 'Oz', aliases: ['mozart'] },
  { id: 'logtalk', name: 'Logtalk' },
  { id: 'datalog', name: 'Datalog' },
  { id: 'souffle', name: 'Souffle' },
  { id: 'dafny', name: 'Dafny' },
  { id: 'fstar', name: 'F*' },
  { id: 'whiley', name: 'Whiley' },
  { id: 'eiffel', name: 'Eiffel' },
  { id: 'sather', name: 'Sather' },
  { id: 'self', name: 'Self' },
  { id: 'newspeak', name: 'Newspeak' },
  { id: 'squirrel', name: 'Squirrel' },
  { id: 'angelscript', name: 'AngelScript' },
  { id: 'chaiscript', name: 'ChaiScript' },
  { id: 'pike', name: 'Pike' },
  { id: 'pawn', name: 'Pawn' },
  { id: 'sourcepawn', name: 'SourcePawn', aliases: ['sp'] },
  { id: 'gml', name: 'GameMaker Language' },
  { id: 'renpy', name: "Ren'Py", aliases: ['rpy'] },
  { id: 'ink', name: 'Ink' },
  { id: 'twee', name: 'Twee' },
  { id: 'inform7', name: 'Inform 7' },
  { id: 'tads', name: 'TADS' },
  { id: 'hugo', name: 'Hugo' },
  { id: 'zimbu', name: 'Zimbu' },
  { id: 'cyclone', name: 'Cyclone' },
  { id: 'cilk', name: 'Cilk' },
  { id: 'chapel', name: 'Chapel' },
  { id: 'x10', name: 'X10' },
  { id: 'fortress', name: 'Fortress' },
  { id: 'parasail', name: 'ParaSail' },
  { id: 'sisal', name: 'SISAL' },
  { id: 'lustre', name: 'Lustre' },
  { id: 'esterel', name: 'Esterel' },
  { id: 'signal', name: 'Signal' },
  { id: 'modelica', name: 'Modelica' },
  { id: 'simulink', name: 'Simulink' },
  { id: 'labview', name: 'LabVIEW' },
  { id: 'scade', name: 'SCADE' },
  { id: 'abc', name: 'ABC' },
  { id: 'beancount', name: 'Beancount' },
  { id: 'ledger', name: 'Ledger' },
  { id: 'hledger', name: 'hledger' },
  { id: 'gnuplot', name: 'Gnuplot' },
  { id: 'postscript', name: 'PostScript', aliases: ['ps'] },
  { id: 'pcb', name: 'PCB' },
  { id: 'gerber', name: 'Gerber' },
  { id: 'gcode', name: 'G-code', aliases: ['nc'] },
  { id: 'stl', name: 'STL' },
  { id: 'openscad', name: 'OpenSCAD' },
  { id: 'pov', name: 'POV-Ray' },
  { id: 'obj', name: 'Wavefront OBJ' },
  { id: 'rib', name: 'RenderMan RIB' },
  { id: 'mel', name: 'MEL' },
  { id: 'maxscript', name: 'MAXScript' },
  { id: 'houdini', name: 'Houdini VEX', aliases: ['vex'] },
  { id: 'nuke', name: 'Nuke TCL' },
  { id: 'shake', name: 'Shake' },
  { id: 'fusion', name: 'Fusion' },
  { id: 'natron', name: 'Natron' },
  { id: 'aftereffects', name: 'After Effects' },
  { id: 'bqn', name: 'BQN' },
  { id: 'apl', name: 'APL' },
  { id: 'j', name: 'J' },
  { id: 'k', name: 'K' },
  { id: 'q', name: 'Q' },
];
